### ISSUE TITLE
I would like to add Code of Conduct markdown file.

### ISSUE THREAD

**Issue by sumitbishti** [iver/ex_aws_secrets#2]

**Comment by iver** [comment]
Thanks for the initiative!

There is already information in the [CONTRIBUTING](cont) document, however, you can improve it, add what you think is prudent and we will review it together.

[cont]: https://github.com/iver/ex_aws_secrets/blob/main/CONTRIBUTING.md

**Comment by sumitbishti** [comment]
Ok, fine then. I'm onto it!
